# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6885d9fae0dce936a058ae46366b9f1c2116995580cecb7ef86a74102b0506fe915fa1069c155c4f6c6851663ef72577322cad222b3480b8b1fc95993ed203d7

test:
  secret_key_base: 804543919fdabcad569bfb5c6248e4f296b99cf1c5349de420f796f939b795c7c61abf61c434fed2d46c56c65af1fc456abc81125cc26c89f31f95debca2a2c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
